import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Rocket } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Casey's Tasks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className="bg-accent sticky top-0 shadow">
          <nav className="mx-auto flex h-50 max-w-[736px] items-center justify-center gap-3 p-3">
            <div className="flex items-center gap-3 text-5xl font-bold">
              <Rocket className="size-8 -rotate-45 text-cyan-500" />
              <span className="text-cyan-500">Todo</span>
              <span className="text-indigo-500">App</span>
            </div>
          </nav>
        </header>
        <div className="mx-auto max-w-[736px]">{children}</div>
      </body>
    </html>
  );
}
